spring:
  application:
    name: gateway
  profiles:
    default: oauth2
server:
  port: 4040
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/